version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres_db:5432/mydatabase"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run start:dev  # Start the NestJS backend

  frontend:
    build:
      context: ./frontend/connectmoney
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "19006:19006"
    depends_on:
      - backend
volumes:
  postgres_data:
